server:
  port: 80


spring:
  application:
    name: nacos-order-consumer

  cloud:
    nacos:
      discovery:
        server-addr: localnacos:8848

service-url:
  nacos-user: http://nacos-payment-provider
