server:
  port: 80


spring:
  application:
    name: nacos-order-consumer

  cloud:
    nacos:
      discovery:
        server-addr: localnacos:1111
    sentinel:
      transport:
        dashboard: seckill.cc:8888
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: seckill.cc:1111
            data-id: ${spring.application.name}
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow

service-url:
  nacos-user: http://nacos-payment-provider


feign:
  sentinel:
    enabled: true
