server:
  port: 8001


spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://mysql_server:3306/db_seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ENC(JQaDTMkm+6SfkR02THGL4ir9FQ+CdlT+Q1c1i1beugd3VVULMR19YBfiksl7+xoP)

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cc.seckill.srpingcloud.entities

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


jasypt:
  encryptor:
#    password:
    algorithm: PBEWITHHMACSHA512ANDAES_256
