server:
  port: 9002


spring:
  application:
    name: nacos-payment-provider

  cloud:
    nacos:
      discovery:
        #        server-addr: localnacos:8848
        server-addr: localnacos:1111  # nacos 集群


management:
  endpoints:
    web:
      exposure:
        include: '*'
