server:
  port: 9001


spring:
  application:
    name: nacos-payment-provider

  cloud:
    nacos:
      discovery:
        #        server-addr: localnacos:8848
        server-addr: localnacos:1111  # nacos 集群
    sentinel:
      transport:
        dashboard: seckill.cc:8888
        port: 8719



management:
  endpoints:
    web:
      exposure:
        include: '*'
